---
title: "CV"
author: "dr. Aldilas Achmad Nursetyo, M.S."
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  html_document:
    df_print: paged
geometry: margin=1.5cm
jobtitle: Researcher, Center for Health Policy & Management, Universitas Gadjah Mada
fontawesome: yes
phone: +62 813 9169 9700
email: mail.aldilas@gmail.com
web: aldeetropolis.github.io
updated: no
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# SUMMARY OF EXPERIENCE

Since 2017, Aldilas has been actively involved in contribute and developing at national and regional level, either academically or direct consultancy. He has experience in developing monitoring and evaluation system in National Family Planning Coordinating Agency (BKKBN) and strengthening national disease surveillance system, especially for early warning and response system (EWARS). He also experienced in research methodology, either quantitative or qualitative methodology, while demonstrating excelence scientific writing and publication experience. Currently, he is active as researcher in Center for Health Policy and Management, Universitas Gadjah Mada, Indonesia.

----

# EDUCATION

*Taipei Medical University*, M.S. Biomedical Informatics \hfill 2017-2019

*Universitas Muhammadiyah Yogyakarta*, M.D. \hfill 2013-2015

*Universitas Muhammadiyah Yogyakarta*, Bachelor of Medicine \hfill 2007-2012

----

# EMPLOYMENT

**Center for Health Policy & Management, Universitas Gadjah Mada**

Researcher \hfill 2016-present

**World Bank Group**

Consultant \hfill 2021-present

**Apotek Viva Generik**

General Practitioner \hfill 2020-2021

**International Center for Health Information Technology, Taipei Medical University**

Research Assistant \hfill 2018-2019

**RSUD Inche Abdoel Moeis, Kota Samarinda**

Internship Medical Doctor \hfill 2015-2016

----

# PROJECTS

**Improving Quality of Disease Preparedness, Surveillance & Response In Indonesia (INSPIRASI)**

*Funded by CDC* \hfill 2021-present

**Researcher** : Analyse Indonesia national health insurance claims on capability to monitor potentially outbreak infectious disease surveillance using time series analysis and data visualization. Designing dashboard presentation of infectious disease surveillance using Indonesia national health insurance claims data to support potentially outbreak infectious disease surveillance program in Indonesia. Writing scientific publication on quality of Early Warning and Response System reporting in primary health care facility. Writing policy brief on implementation of Public Health Emergency Operation Center in regional settings.

**Integrated Health Surveillance System Supporting Covid-19 Emergency Response Operations**

*Funded by World Bank Group* \hfill 2021-2022

**Consultant**: Analyse workflow of Allrecord TC-19, an application used by Indonesia government to collect PCR and rapid antigen result for COVID-19 surveillance. Building online user guideline for Allrecord TC-19 application to help user get the update from the app. Held two batch of one week FHIR workshops for public/private hospitals, HIMS vendors, and healthcare startups.

**Evaluation of Healthcare Gaps in Indonesian Health System**

*African Medical and Research Foundation (AMREF)* \hfill 2022

**Co - Principal Investigator**: Assisting Principal Investigator in conducting evaluation of healthcare system gaps with a focus on IBD, cancer, rare diseases and PDT treatment in Indonesia; Developing both quantitative and qualitative data collection methods from the stakeholders including governmental authorities, public and private healthcare providers (hospitals and primary care), healthcare NGOs, pharmaceutical companies; Coordinating field researcher in conducting data collection at national and regional level.

**Post-Abortion Care Supply Chain Management Assesment in Indonesia**

*Funded by Ipas* \hfill 2020

**Consultant** : Conducting Post-Abortion Care Supply Chain Management assesment in Indonesia involving MoH, public health office staffs, public health center staffs, hospital staffs, and post-abortion care logistics supplier.; Responsible for designing methodology and instruments.; Responsible for data quantitative and qualitative data collection and analysis.

**Evaluation of Clinical Pathway Implementation in General Hospital in Indonesia**

*Funded by Research and Development Ministry of Health Indonesia* \hfill 2019

**Field Researcher Coordinator** : Coordinating with Principal Investigator in conducting data collection in the field; Coordination with the hospital for data collection procedure; Coordination with several enumerator for conduction data collection; Preparing qualitative data collection report (transription and verbatim) to Principal Investigator.

**Developing Monitoring and Evaluation System for Family Planning Program in National Family Planning Coordinating Agency (BKKBN)**

*Funded by Bill-Melinda Gates Foundation (BMGF)* \hfill 2016-2017

**Information Technology Specialist** : Doing needs assesment on monitoring and evaluation capacity in BKKBN. Then from the assesment result, designing monitoring and evaluation information system in national, regional, and district levels.

----

# PUBLICATIONS

Rahmanti, A. R., Yang, H.-C., Bintoro, B. S., Nursetyo, A. A., Muhtar, M. S., Syed-Abdul, S., & Li, Y.-C. J. (2022). SlimMe, a Chatbot With Artificial Empathy for Personal Weight Management: System Design and Finding. Frontiers in Nutrition, 9, 870775. https://doi.org/10.3389/fnut.2022.870775

Rahmanti, A. R., Chien, C.-H., Nursetyo, A. A., Husnayain, A., Wiratama, B. S., Fuad, A., Yang, H.-C., & Li, Y.-C. J. (2022). Social media sentiment analysis to monitor the performance of vaccination coverage during the early phase of the national COVID-19 vaccine rollout. Computer Methods and Programs in Biomedicine, 221, 106838. https://doi.org/10.1016/j.cmpb.2022.106838

Nanda, R. O., Nursetyo, A. A., Ramadona, A. L., Imron, M. A., Fuad, A., Setyawan, A., & Ahmad, R. A. (2022). Community Mobility and COVID-19 Dynamics in Jakarta, Indonesia. International Journal of Environmental Research and Public Health, 19(11), 6671. https://doi.org/10.3390/ijerph19116671

Hardhantyo, M., Djasri, H., Nursetyo, A. A., Yulianti, A., Adipradipta, B. R., Hawley, W., Mika, J., Praptiningsih, C. Y., Mangiri, A., Prasetyowati, E. B., & Brye, L. (2022). Quality of National Disease Surveillance Reporting before and during COVID-19: A Mixed-Method Study in Indonesia. International Journal of Environmental Research and Public Health, 19(5), 2728. https://doi.org/10.3390/ijerph19052728

Dovgan, E., Gradišek, A., Luštrek, M., Uddin, M., Nursetyo, A. A., Annavarajula, S. K., Li, Y.-C., & Syed-Abdul, S. (2020). Using machine learning models to predict the initiation of renal replacement therapy among chronic kidney disease patients. PLOS ONE, 15(6), e0233976. https://doi.org/10.1371/journal.pone.0233976

Syed-Abdul, S., Malwade, S., Nursetyo, A. A., Sood, M., Bhatia, M., Barsasella, D., Liu, M. F., Chang, C.-C., Srinivasan, K., M., R., & Li, Y.-C. J. (2019). Virtual reality among the elderly: A usefulness and acceptance study from Taiwan. BMC Geriatrics, 19(1), 223. https://doi.org/10.1186/s12877-019-1218-8

Nursetyo, A. A., Syed-Abdul, S., Uddin, M., & Li, Y.-C. J. (2019). Graft Rejection Prediction Following Kidney Transplantation Using Machine Learning Techniques: A Systematic Review and Meta-Analysis. Studies in Health Technology and Informatics, 264, 10–14. https://doi.org/10.3233/SHTI190173

Putra, F. R., Nursetyo, A. A., Thakur, S. S., Roy, R. B., Syed-Abdul, S., Malwade, S., & Li, Y.-C. J. (2019). Prediction of Clinical Events in Hemodialysis Patients Using an Artificial Neural Network. Studies in Health Technology and Informatics, 264, 1570–1571. https://doi.org/10.3233/SHTI190539

Thakur, S. S., Abdul, S. S., Chiu, H.-Y. (Shannon), Roy, R. B., Huang, P.-Y., Malwade, S., Nursetyo, A. A., & Li, Y.-C. (Jack). (2018). Artificial-Intelligence-Based Prediction of Clinical Events among Hemodialysis Patients Using Non-Contact Sensor Data. Sensors, 18(9), 2833. https://doi.org/10.3390/s18092833

Ganapathy, K., Abdul, S., & Nursetyo, A. (2018). Artificial intelligence in neurosciences: A clinician’s perspective. Neurology India, 66(4), 934. https://doi.org/10.4103/0028-3886.236971

Malwade, S., Abdul, S. S., Uddin, M., Nursetyo, A. A., Fernandez-Luque, L., Zhu, X. (Katie), Cilliers, L., Wong, C.-P., Bamidis, P., & Li, Y.-C. (Jack). (2018). Mobile and wearable technologies in healthcare for the ageing population. Computer Methods and Programs in Biomedicine, 161, 233–237. https://doi.org/10.1016/j.cmpb.2018.04.026

Nurwanti, E., Uddin, M., Chang, J.-S., Hadi, H., Syed-Abdul, S., Su, E., Nursetyo, A., Masud, J., & Bai, C.-H. (2018). Roles of Sedentary Behaviors and Unhealthy Foods in Increasing the Obesity Risk in Adult Men and Women: A Cross-Sectional National Study. Nutrients, 10(6), 704. https://doi.org/10.3390/nu10060704
